<?php

namespace MKTBundle\Repository;

/**
 * MKTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MKTRepository extends \Doctrine\ORM\EntityRepository
{
}
